<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn></NoWarn>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1.0</InformationalVersion>
    <Company>CorePin</Company>
    <Product>CorePin</Product>
  </PropertyGroup>
</Project>
